Simcha 2d conv
KRappaport/Hardware-Convolution pull request #6
Opened 2018-06-07 09:52 UTC by simchaherschman

I believe this is good to go for testing on the hardware

CHeck it out and let me knpw what you think

I think we should run tests comparing:
1. our methods against each other
2. our methods with parfor against each other
3. somehow do shoups algorithm....

2018-06-07 09:55 UTC, simchaherschman commented
Note: major change in the runtemplate is that for the Matlab result, I did a total of 3   2-d convolutions set in a for loop. This is also how I calculated the result in my convolution

2018-06-11 15:14 UTC, KRappaport commented
I just tested your function and compared your results against MATLAB's and they are very different, so I don't think it is ready to be merged.  In addition the final result of your function should sum up the matrices on the 3rd dimension returning a single 2D matrix.  

Also just a heads up that your run_template is going to be deleted and after this branch is merged to master I will add it to the new set of run_templates.

2018-06-12 14:59 UTC, KRappaport requested changes
The output of conv2d should be a 2D matrix.

2018-07-15 07:27 UTC, KRappaport approved these changes

2018-07-15 07:33 UTC, merged